version: "3.9"
services:
  dev:
    build: .
    ports:
      - 8887:8887
      - 8888:8888
      - 22700:22700
      - 8896:8896
      - 6006:6006
    tty: true
    privileged: true
    volumes:
      - $PWD:/home/code
      - $MSYNTH_DATA/:/home/data
      - $HOME/.config/pulse:/home/.config/pulse
      - $HOME/:/home/mac
    environment:
      - PULSE_SERVER=docker.for.mac.localhost
      - DISPLAY=host.docker.internal:0
    user: "0"
volumes:
    data:
