epsilon: 0.001
log_wandb: True
num_notes: 16
num_avg: 20
learning_rate: 0.01 
recurrent: True
recurrent_aggregate: False
apply_softmax: False
apply_sigmoid: True
apply_gumbelsoftmax : False
real_gradient: True
freq_version: True
pyfluidsynth: 1.0
reshape_version: False
avgpool_version: False
num_iterations: 6000
device: 'cuda'
seed: 1